# post Makefile

#include ./macros.make

all: 
	$(MAKE) -C bacio
	$(MAKE) -C gribio
	$(MAKE) -C slint
	$(MAKE) -C pop

clean:
	$(MAKE) -C bacio     clean
	$(MAKE) -C gribio    clean
	$(MAKE) -C slint     clean
	$(MAKE) -C pop       clean
